[tool.poetry]
name = "torch-kfac"
version = "0.1.0"
authors = []
packages = [
    { include = "torch_kfac", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.7"
torch = ">0.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

